In [3]:
import torch
torch.cuda.is_available()

True

In [5]:
torch.backends.cudnn.version()

8200

In [7]:
import gc
gc.collect()
print(type(gc))

<class 'module'>


In [4]:

import numpy as np
a = torch.Tensor(np.arange(24).reshape(2,3,4)) 
b = torch.Tensor(np.arange(24).reshape(2,3,4)) 
print(a*b)
(a*b).mean(dim=1)

tensor([[[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.]],

        [[144., 169., 196., 225.],
         [256., 289., 324., 361.],
         [400., 441., 484., 529.]]])


tensor([[ 26.6667,  35.6667,  46.6667,  59.6667],
        [266.6667, 299.6667, 334.6667, 371.6667]])

In [ ]:
import cv2


cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 2560)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 960)
fps = cap.get(cv2.CAP_PROP_FPS)



fourcc = cv2.VideoWriter_fourcc(*'DIVX')
out = cv2.VideoWriter('output.avi', fourcc, fps, (2560, 960))


while True:
    ret, frame = cap.read()
    frame = cv2.flip(frame,0)
    cv2.imshow('frame',frame)

    out.write(frame) 
    if cv2.waitKey(1) == 27:
        break
out.release()
cap.release()
cv2.destroyAllWindows()


In [9]:
import numpy as np

a = np.arange(12).reshape(3,4)
print(a)
b = 3 + a
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [8]:
a = [1,2]
b = (1,2)
print(type(a), type(b))


<class 'list'> <class 'tuple'>


In [17]:
np.random.binomial(4,0.5,10)

array([3, 4, 2, 2, 4, 2, 3, 2, 2, 1])

In [20]:
a = np.arange(9).reshape(3,3)
b = np.mean(a,0)
c = np.mean(np.mean(a,0))
d = np.mean(np.mean(a,0),0)[np.newaxis, np.newaxis]
a[:] = 3
print(a, b, c, d, d.shape) 

[[3 3 3]
 [3 3 3]
 [3 3 3]] [3. 4. 5.] 4.0 [[4.]] (1, 1)


In [26]:
import torchvision.transforms as transforms

In [36]:
a = np.arange(75).reshape(5,5,3) 
print(a.shape)
b = a[0:2, 1:3]
print(b, b.shape)

(5, 5, 3)
[[[ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]]] (2, 2, 3)


In [41]:
a = np.arange(300,dtype = np.float32).reshape(10,10,3) 
 
def get_transform():
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]

    return transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean=mean, std=std),
    ])
b = get_transform()
print(a.shape, type(b))
print(b(a).shape)

(10, 10, 3) <class 'torchvision.transforms.transforms.Compose'>
torch.Size([3, 10, 10])
