In [10]:
import torch
torch.cuda.is_available()

True

In [18]:

import numpy as np
a = torch.Tensor(np.arange(24).reshape(2,3,4)) 
b = torch.Tensor(np.arange(24).reshape(2,3,4)) 
print(a*b)
(a*b).mean(dim=1)

tensor([[[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.]],

        [[144., 169., 196., 225.],
         [256., 289., 324., 361.],
         [400., 441., 484., 529.]]])


tensor([[ 26.6667,  35.6667,  46.6667,  59.6667],
        [266.6667, 299.6667, 334.6667, 371.6667]])

In [ ]:
import cv2


cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 2560)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 960)
fps = cap.get(cv2.CAP_PROP_FPS)



fourcc = cv2.VideoWriter_fourcc(*'DIVX')
out = cv2.VideoWriter('output.avi', fourcc, fps, (2560, 960))


while True:
    ret, frame = cap.read()
    frame = cv2.flip(frame,0)
    cv2.imshow('frame',frame)

    out.write(frame) 
    if cv2.waitKey(1) == 27:
        break
out.release()
cap.release()
cv2.destroyAllWindows()


In [4]:
import numpy as np

a = np.arange(12).reshape(3,4)
print(a)
b = 3 + a
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])